package gui.menu;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import gui.panelesMenu.Panel_Categoria;
import gui.panelesMenu.Panel_Mesa;
import gui.panelesMenu.Panel_PlatoMenu;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.awt.Insets;




public class Frm_MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frm_MenuPrincipal.class.getName());

    public Frm_MenuPrincipal() {
                
        
        UIManager.put("TabbedPane.tabAreaInsets", new Insets(10, 40, 10, 10));
        UIManager.put("TabbedPane.tabInsets", new Insets(0, 0, 0, 0));
        
        // También elimina el espacio que Swing deja para el área de contenido
        UIManager.put("TabbedPane.contentBorderInsets", new Insets(0, 0, 0, 0));
        FlatLightLaf.setup();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menú Principal");
        this.setResizable(false);
        
                                                                categoria_content.setOpaque(false);
                                                                mesa_content.setOpaque(false);
                                                                platoMenu_content.setOpaque(false);
                                                                cargo_content.setOpaque(false);
                                                                cliente_content.setOpaque(false);
                                                                contrato_content.setOpaque(false);
                                                                detallepedido_content.setOpaque(false);
                                                                empleado_content.setOpaque(false);
                                                                factura_content.setOpaque(false);
                                                                pedido_content.setOpaque(false);
                                                                producto_content.setOpaque(false);
                                                                proveedor_producto_content.setOpaque(false);
                                                                proveedor_content.setOpaque(false);
                                                                reserva_content.setOpaque(false);
        
        // El primer número (0, 1, 2...) es el índice de la pestaña
        jTabbedPanePrincipal.setIconAt(0, redimensionarIcono("/assets/botoncategoria.png",120,46));
        jTabbedPanePrincipal.setIconAt(1, redimensionarIcono("/assets/botonmesa.png",120,46));
        jTabbedPanePrincipal.setIconAt(2, redimensionarIcono("/assets/botonplatomenu.png",120,46));
        jTabbedPanePrincipal.setIconAt(3, redimensionarIcono("/assets/botoncargo.png",120,46));
        jTabbedPanePrincipal.setIconAt(4, redimensionarIcono("/assets/botonclientes.png",120,46));
        jTabbedPanePrincipal.setIconAt(5, redimensionarIcono("/assets/botoncontrato.png",120,46));
        jTabbedPanePrincipal.setIconAt(6, redimensionarIcono("/assets/botondetallepedido.png",120,46));
        jTabbedPanePrincipal.setIconAt(7, redimensionarIcono("/assets/botonempleado.png",120,46));
        jTabbedPanePrincipal.setIconAt(8, redimensionarIcono("/assets/botonfactura.png",120,46));
        jTabbedPanePrincipal.setIconAt(9, redimensionarIcono("/assets/botonpedido.png",120,46));
        jTabbedPanePrincipal.setIconAt(10, redimensionarIcono("/assets/botonproducto.png",120,46));
        jTabbedPanePrincipal.setIconAt(11, redimensionarIcono("/assets/botonprov-producto.png",120,46));
        jTabbedPanePrincipal.setIconAt(12, redimensionarIcono("/assets/botonproveedor.png",120,46));
        jTabbedPanePrincipal.setIconAt(13, redimensionarIcono("/assets/botonreserva.png",120,46));
        
        jTabbedPanePrincipal.setOpaque(false); // Hace el contenedor transparente
        jTabbedPanePrincipal.setBackground(new Color(0, 0, 0, 0)); // Color con Alpha 0
        
        Panel_Categoria categoria_menu = new Panel_Categoria();
        categoria_content.add(categoria_menu);
        Panel_Mesa mesa_menu = new Panel_Mesa();
        mesa_content.add(mesa_menu);
        Panel_PlatoMenu platoMenu = new Panel_PlatoMenu();
        platoMenu_content.add(platoMenu);
        jTabbedPanePrincipal.revalidate();
        jTabbedPanePrincipal.repaint();
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        balloonManager1 = new org.edisoncor.gui.util.BalloonManager();
        balloonManager2 = new org.edisoncor.gui.util.BalloonManager();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        ItemUsuario = new javax.swing.JMenuItem();
        ItemCliente = new javax.swing.JMenuItem();
        ItemProducto = new javax.swing.JMenuItem();
        ItemProveedor = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcerca = new javax.swing.JMenuItem();
        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        categoria_content = new javax.swing.JPanel();
        mesa_content = new javax.swing.JPanel();
        platoMenu_content = new javax.swing.JPanel();
        cargo_content = new javax.swing.JPanel();
        cliente_content = new javax.swing.JPanel();
        contrato_content = new javax.swing.JPanel();
        detallepedido_content = new javax.swing.JPanel();
        empleado_content = new javax.swing.JPanel();
        factura_content = new javax.swing.JPanel();
        pedido_content = new javax.swing.JPanel();
        producto_content = new javax.swing.JPanel();
        proveedor_producto_content = new javax.swing.JPanel();
        proveedor_content = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        reserva_content = new javax.swing.JPanel();
        panelContent = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        panelImageReflect1 = new org.edisoncor.gui.panel.PanelImageReflect();
        panelImageReflect2 = new org.edisoncor.gui.panel.PanelImageReflect();
        BTN_Cerrar1 = new javax.swing.JButton();
        jCalendar3 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuArchivo1 = new javax.swing.JMenu();
        itemSalir1 = new javax.swing.JMenuItem();
        menuMantenimiento1 = new javax.swing.JMenu();
        ItemUsuario1 = new javax.swing.JMenuItem();
        ItemCliente1 = new javax.swing.JMenuItem();
        ItemProducto1 = new javax.swing.JMenuItem();
        ItemProveedor1 = new javax.swing.JMenuItem();
        menuAyuda1 = new javax.swing.JMenu();
        itemAcerca1 = new javax.swing.JMenuItem();

        menuArchivo.setText("Archivo");

        itemSalir.setText("Salir");
        itemSalir.addActionListener(this::itemSalirActionPerformed);
        menuArchivo.add(itemSalir);

        jMenuBar1.add(menuArchivo);

        menuMantenimiento.setText("Mantenimiento");

        ItemUsuario.setText("Usuario");
        ItemUsuario.addActionListener(this::ItemUsuarioActionPerformed);
        menuMantenimiento.add(ItemUsuario);

        ItemCliente.setText("Cliente");
        ItemCliente.addActionListener(this::ItemClienteActionPerformed);
        menuMantenimiento.add(ItemCliente);

        ItemProducto.setText("Producto");
        menuMantenimiento.add(ItemProducto);

        ItemProveedor.setText("Proveedor");
        menuMantenimiento.add(ItemProveedor);

        jMenuBar1.add(menuMantenimiento);

        menuAyuda.setText("Ayuda");

        itemAcerca.setText("Acerca de");
        itemAcerca.addActionListener(this::itemAcercaActionPerformed);
        menuAyuda.add(itemAcerca);

        jMenuBar1.add(menuAyuda);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPanePrincipal.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPanePrincipal.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        categoria_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", categoria_content);

        mesa_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", mesa_content);

        platoMenu_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", platoMenu_content);

        cargo_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", cargo_content);

        cliente_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", cliente_content);

        contrato_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", contrato_content);

        detallepedido_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", detallepedido_content);

        empleado_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", empleado_content);

        factura_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", factura_content);

        pedido_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", pedido_content);

        producto_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", producto_content);

        proveedor_producto_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", proveedor_producto_content);

        proveedor_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", proveedor_content);

        jPanel12.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", jPanel12);

        reserva_content.setLayout(new java.awt.GridBagLayout());
        jTabbedPanePrincipal.addTab("", reserva_content);

        getContentPane().add(jTabbedPanePrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1140, 730));

        panelContent.setBackground(new java.awt.Color(0, 0, 0));
        panelContent.setForeground(new java.awt.Color(255, 255, 255));
        panelContent.setOpaque(false);
        panelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCalendar1.setBackground(new java.awt.Color(102, 102, 102));
        panelContent.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, -1, -1));
        panelContent.add(jCalendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 120, 250, 200));
        panelContent.add(panelImageReflect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));
        panelContent.add(panelImageReflect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        BTN_Cerrar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon_close.png"))); // NOI18N
        BTN_Cerrar1.setText("   CERRAR");
        BTN_Cerrar1.addActionListener(this::BTN_Cerrar1ActionPerformed);
        panelContent.add(BTN_Cerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 150, 40));

        jCalendar3.setFocusable(false);
        jCalendar3.setOpaque(false);
        jCalendar3.setRequestFocusEnabled(false);
        jCalendar3.setVerifyInputWhenFocusTarget(false);
        jCalendar3.setWeekOfYearVisible(false);
        panelContent.add(jCalendar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 180));

        getContentPane().add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 50, 190, 680));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 760));

        menuArchivo1.setText("Archivo");

        itemSalir1.setText("Salir");
        itemSalir1.addActionListener(this::itemSalir1ActionPerformed);
        menuArchivo1.add(itemSalir1);

        jMenuBar2.add(menuArchivo1);

        menuMantenimiento1.setText("Mantenimiento");

        ItemUsuario1.setText("Usuario");
        ItemUsuario1.addActionListener(this::ItemUsuario1ActionPerformed);
        menuMantenimiento1.add(ItemUsuario1);

        ItemCliente1.setText("Cliente");
        ItemCliente1.addActionListener(this::ItemCliente1ActionPerformed);
        menuMantenimiento1.add(ItemCliente1);

        ItemProducto1.setText("Producto");
        menuMantenimiento1.add(ItemProducto1);

        ItemProveedor1.setText("Proveedor");
        menuMantenimiento1.add(ItemProveedor1);

        jMenuBar2.add(menuMantenimiento1);

        menuAyuda1.setText("Ayuda");

        itemAcerca1.setText("Acerca de");
        itemAcerca1.addActionListener(this::itemAcerca1ActionPerformed);
        menuAyuda1.add(itemAcerca1);

        jMenuBar2.add(menuAyuda1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public ImageIcon redimensionarIcono(String path, int width, int height) {
    // 1. Cargar la imagen desde el paquete de assets
    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(path));
    
    // 2. Extraer la imagen y escalarla con suavizado (Smooth) para que no se vea pixelada
    Image imgEscalada = iconoOriginal.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
    
    // 3. Retornar el nuevo icono
    return new ImageIcon(imgEscalada);
}
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_itemSalirActionPerformed

    private void ItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuarioActionPerformed
        //Frm_Usuario frm = new Frm_Usuario();
        //frm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ItemUsuarioActionPerformed

    private void ItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemClienteActionPerformed

    private void itemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaActionPerformed
        JOptionPane.showMessageDialog(this, "Bienvenido al sistema");        // TODO add your handling code here:
    }//GEN-LAST:event_itemAcercaActionPerformed

    private void itemSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalir1ActionPerformed

    private void ItemUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemUsuario1ActionPerformed
        //Frm_Usuario frm = new Frm_Usuario();
        //frm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ItemUsuario1ActionPerformed

    private void ItemCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemCliente1ActionPerformed

    private void itemAcerca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcerca1ActionPerformed
        JOptionPane.showMessageDialog(this, "Bienvenido al sistema");        // TODO add your handling code here:
    }//GEN-LAST:event_itemAcerca1ActionPerformed

    private void BTN_Cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Cerrar1ActionPerformed

        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Estás seguro de que deseas cerrar el formulario?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                // Cerrar conexión si tienes un método cerrarConexion()
                //TODO --> conexion.cerrarConexion();
            } catch (Exception e) {
                System.err.println("Error al cerrar la conexión: " + e.getMessage());
            }
            // Cierra el formulario actual
            dispose(); // o this.dispose() si estás dentro del formulario
        }
    }//GEN-LAST:event_BTN_Cerrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frm_MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar1;
    private javax.swing.JMenuItem ItemCliente;
    private javax.swing.JMenuItem ItemCliente1;
    private javax.swing.JMenuItem ItemProducto;
    private javax.swing.JMenuItem ItemProducto1;
    private javax.swing.JMenuItem ItemProveedor;
    private javax.swing.JMenuItem ItemProveedor1;
    private javax.swing.JMenuItem ItemUsuario;
    private javax.swing.JMenuItem ItemUsuario1;
    private org.edisoncor.gui.util.BalloonManager balloonManager1;
    private org.edisoncor.gui.util.BalloonManager balloonManager2;
    private javax.swing.JPanel cargo_content;
    private javax.swing.JPanel categoria_content;
    private javax.swing.JPanel cliente_content;
    private javax.swing.JPanel contrato_content;
    private javax.swing.JPanel detallepedido_content;
    private javax.swing.JPanel empleado_content;
    private javax.swing.JPanel factura_content;
    private javax.swing.JMenuItem itemAcerca;
    private javax.swing.JMenuItem itemAcerca1;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemSalir1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private com.toedter.calendar.JCalendar jCalendar3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuArchivo1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuAyuda1;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenu menuMantenimiento1;
    private javax.swing.JPanel mesa_content;
    private javax.swing.JPanel panelContent;
    private org.edisoncor.gui.panel.PanelImageReflect panelImageReflect1;
    private org.edisoncor.gui.panel.PanelImageReflect panelImageReflect2;
    private javax.swing.JPanel pedido_content;
    private javax.swing.JPanel platoMenu_content;
    private javax.swing.JPanel producto_content;
    private javax.swing.JPanel proveedor_content;
    private javax.swing.JPanel proveedor_producto_content;
    private javax.swing.JPanel reserva_content;
    // End of variables declaration//GEN-END:variables
}
