/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.crudMantenimiento;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.table.DefaultTableModel;
import logic.dao.FacturaMethod;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author ETHAN
 */
public class JD_BuscarPedido extends javax.swing.JDialog {
    
    // 1. Variable para referenciar al formulario que te llamó
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JD_BuscarPedido.class.getName());
    DefaultTableModel modeloTablaPedido;
    FacturaMethod FC = new FacturaMethod();
    private gui.crudMantenimiento.Frm_Factura formularioPadre;

    public JD_BuscarPedido(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    FlatLightLaf.setup();
    initComponents();
    this.setLocationRelativeTo(null);

    
    // Solo asignamos si el padre es realmente la factura
    if (parent instanceof gui.crudMantenimiento.Frm_Factura) {
        this.formularioPadre = (gui.crudMantenimiento.Frm_Factura) parent;
    }
    
    // Configurar el modelo de la tabla
    String[] titulos = {"ID", "Fecha", "DNI Cli", "Nombre Cli", "Apellidos Cli", "DNI Emp", "Nombre Emp", "Apellidos Emp", "Cliente", "Empleado", "Tipo", "Platos"};
    modeloTablaPedido = new DefaultTableModel(null, titulos);
    jTable1.setModel(modeloTablaPedido);
    
    listarPedidos();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonCerrar = new javax.swing.JButton();
        jButtonElegir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TXT_BuscarPedidos = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccionar Empleado");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCerrar.setText("CERRAR");
        jButtonCerrar.addActionListener(this::jButtonCerrarActionPerformed);
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 140, 40));

        jButtonElegir.setText("ELEGIR");
        jButtonElegir.addActionListener(this::jButtonElegirActionPerformed);
        getContentPane().add(jButtonElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 140, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccionar Pedido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 430, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1010, 210));

        jLabel1.setText("BUSCAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        TXT_BuscarPedidos.addActionListener(this::TXT_BuscarPedidosActionPerformed);
        TXT_BuscarPedidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarPedidosKeyReleased(evt);
            }
        });
        jPanel1.add(TXT_BuscarPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 340, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                                    
    // Si el usuario hace doble clic en una fila
    if (evt.getClickCount() == 2) {
        int fila = jTable1.getSelectedRow();
        if (fila != -1) {
            // 1. Extraemos los datos de las columnas específicas
            // ID (Col 0), Cliente CONCAT (Col 8), Empleado CONCAT (Col 9)
            String idPedido = jTable1.getValueAt(fila, 0).toString();
            String clienteFull = jTable1.getValueAt(fila, 8).toString();
            String empleadoFull = jTable1.getValueAt(fila, 9).toString();

            // 2. Pasamos los datos al formulario padre
            // Asegúrate de que estos componentes en Frm_Factura1 sean PUBLIC
            formularioPadre.TXT_idPedido.setText(idPedido);
            formularioPadre.seleccionarEnCombo(formularioPadre.jComboBox_Cliente, clienteFull);
            formularioPadre.seleccionarEnCombo(formularioPadre.jComboBox_Empleado, empleadoFull);

            // 3. Cerramos el diálogo
            this.dispose();
        }
    }

    }//GEN-LAST:event_jTable1MouseClicked

    private void TXT_BuscarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_BuscarPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_BuscarPedidosActionPerformed

    private void TXT_BuscarPedidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarPedidosKeyReleased
        this.buscarPedido();
    }//GEN-LAST:event_TXT_BuscarPedidosKeyReleased

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonElegirActionPerformed
    int fila = jTable1.getSelectedRow();
    if (fila != -1) {
        // Como el RowSorter puede cambiar el orden visual, usamos convertRowIndexToModel
        int filaReal = jTable1.convertRowIndexToModel(fila);
        
        String idPedido = modeloTablaPedido.getValueAt(filaReal, 0).toString();
        String clienteFull = modeloTablaPedido.getValueAt(filaReal, 8).toString();
        String empleadoFull = modeloTablaPedido.getValueAt(filaReal, 9).toString();

        formularioPadre.TXT_idPedido.setText(idPedido);
        formularioPadre.seleccionarEnCombo(formularioPadre.jComboBox_Cliente, clienteFull);
        formularioPadre.seleccionarEnCombo(formularioPadre.jComboBox_Empleado, empleadoFull);

        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un pedido de la tabla.");
    }

    }//GEN-LAST:event_jButtonElegirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JD_BuscarPedido dialog = new JD_BuscarPedido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXT_BuscarPedidos;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonElegir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void listarPedidos() {
    try {
        // 1. Limpiar tabla y activar buscador
        jTable1.setAutoCreateRowSorter(true);
        modeloTablaPedido.setRowCount(0);

        // 2. Obtener datos (Usamos la instancia de tu clase de métodos, ej: FC)
        // Asegúrate de que FC esté disponible o instanciado aquí
        ResultSet rs = FC.listarPedidos(); 

        while (rs.next()) {
            Object fila[] = {
                rs.getInt("ID"),
                rs.getString("Fecha del Pedido"),
                rs.getString("DNI del Cliente"),
                rs.getString("Nombre del Cliente"),
                rs.getString("Apellidos del Cliente"),
                rs.getString("DNI del Empleado"),
                rs.getString("Nombre del Empleado"),
                rs.getString("Apellidos del Empleado"),
                rs.getString("Cliente"), // Este es el CONCAT que usaremos para el Combo
                rs.getString("Empleado"), // Este es el CONCAT que usaremos para el Combo
                rs.getString("Tipo de Pedido"),
                rs.getInt("Cantidad de Platos")
            };
            modeloTablaPedido.addRow(fila);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar pedidos: " + e.getMessage());
    }
}

    private void buscarPedido() {
        String texto = TXT_BuscarPedidos.getText().toLowerCase();
        // Filtro simple usando RowSorter
        javax.swing.table.TableRowSorter<DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(modeloTablaPedido);
        jTable1.setRowSorter(sorter);
        sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
    }
}
