/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assets;

import java.awt.Color;
import com.formdev.flatlaf.FlatLightLaf;

public class Frm_LoginAcceso extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frm_LoginAcceso.class.getName());

    
    public Frm_LoginAcceso() {
        this.setUndecorated(true);
        FlatLightLaf.setup();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
   
        txtUsuario.setOpaque(false);
        txtPassword.setOpaque(true);
    
        
        txtUsuario.setOpaque(false); // Hace el fondo transparente
        txtUsuario.setBackground(new Color(0, 0, 0, 0)); // Refuerza la transparencia
        txtUsuario.setBorder(null); // Quita la línea del borde si no la necesitas
        
        txtPassword.setOpaque(false); // Hace el fondo transparente
        txtPassword.setBackground(new Color(0, 0, 0, 0)); // Refuerza la transparencia
        txtPassword.setBorder(null); // Quita la línea del borde si no la necesitas

        login.setOpaque(false); // Hace el fondo transparente
        login.setBackground(new Color(0, 0, 0, 0)); // Refuerza la transparencia
        login.setBorder(null); // Quita la línea del borde si no la necesitas
        
        
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        chkMostrar = new javax.swing.JCheckBox();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        cbCargo = new javax.swing.JComboBox<>();
        btnIngresar = new javax.swing.JButton();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        btnSalir = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(51, 51, 51));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);
        login.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 200, 30));

        txtPassword.setBackground(new java.awt.Color(0, 0, 0));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        login.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 200, 30));
        login.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 210, 10));

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        login.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 60, -1));

        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username");
        login.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));
        login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 210, 10));

        chkMostrar.addActionListener(this::chkMostrarActionPerformed);
        login.add(chkMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 20, 20));

        panelImage1.setForeground(new java.awt.Color(255, 255, 255));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login_icon.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        login.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 140));

        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar cargo", "Administrador", "Cajero", "Mesero", "Cocinero" }));
        cbCargo.setBorder(null);
        login.add(cbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 190, 30));

        btnIngresar.setBackground(new java.awt.Color(13, 48, 193));
        btnIngresar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);
        login.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 120, 40));

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon_eye.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        login.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 20, 20));

        btnSalir.setBackground(new java.awt.Color(13, 48, 193));
        btnSalir.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        login.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 120, 40));

        PanelFondo.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 430, 450));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/login_background.jpg"))); // NOI18N
        lblFondo.setText("jLabel1");
        PanelFondo.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 480));

        getContentPane().add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarActionPerformed
        if (chkMostrar.isSelected()) {
            txtPassword.setEchoChar((char)0); // muestra
        } else {
            txtPassword.setEchoChar('•'); // oculta
        }
    }//GEN-LAST:event_chkMostrarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frm_LoginAcceso().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JCheckBox chkMostrar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel login;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
